/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: motaman (https://sketchfab.com/motaman)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spaceship-0a073d0ab9a64b408056e82f7628b188
Title: Spaceship
*/

import React, { useRef } from 'react'
import { useAnimations, useGLTF } from '@react-three/drei';

import rocketScene from '../assets/3d/rocket.glb'

const Rocket = ({isRotating, ...props})=> {
    const {scene, animations} = useGLTF(rocketScene);
    const ref = useRef();
    const {actions} = useAnimations(animations,ref);
    

  return (
    <mesh {...props} ref={ref}>
        <primitive object = {scene}/>
    </mesh>
  )
}

export default Rocket
